### ISSUE TITLE
Terrain shading error code

### ISSUE THREAD

**Issue by BebeCyanure** [zoran-cuckovic/QGIS-terrain-shading#18]
Hello. I'm not sure where to post this, so I'm using this platform. Apologies if this is not the appropriate way of bringing this issue up.
I'm getting the following error message when I try to run the Terrain Shader. I have no idea how to fix it. Thank you.

```
Traceback (most recent call last):
File "C:\Users/aan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\TerrainShading\hillshade_algorithm.py", line 250, in processAlgorithm
dem.rst.ReadAsArray(*gdal_take, mx_z[mx_view_in])
File "C:\OSGeo4W\apps\Python39\lib\site-packages\GDAL-3.4.3-py3.9-win-amd64.egg\osgeo\gdal.py", line 2338, in ReadAsArray
return gdal_array.DatasetReadAsArray(self, xoff, yoff, xsize, ysize, buf_obj,
File "C:\OSGeo4W\apps\Python39\lib\site-packages\GDAL-3.4.3-py3.9-win-amd64.egg\osgeo\gdal_array.py", line 297, in DatasetReadAsArray
raise ValueError('Array should have 3 dimensions')
ValueError: Array should have 3 dimensions

Execution failed after 0.03 seconds
```

**Comment by BebeCyanure** [comment]
The DEM I was using was corrupted. The plugin works perfectly well. Thank you.
